### PR TITLE
Windows compatibility fixes

### PR DESCRIPTION
**Pull request by RobotCaleb**
I have made various changes to the source to support windows. My current setup is to not use your cmake configuration and instead include the source files into our project. Therefore, I have no cmake changes in this.

High level:
 - use C++11 PRNG
 - localtime_r wasn't available, debug on windows doesn't include timestamp
 - windows sockets aren't file descriptors per se, don't call write() instead call send()
 - don't handle sigpipe
 - intialize and shutdown winsock

### CODE REVIEW

**Comment by m-mizutani** [comment]
Thanks for sending PR. The PR looks almost great to me. But I have two request before merging the PR.

1. Could you use `InetEmitter::init`instead of `InetEmitter::Init` according to name convention of the project?
2. [travis CI](https://travis-ci.org/m-mizutani/libfluent/builds/193512793) says the patch can not be compiled in Linux and macOS environment. Could you fix the error before merging? If you don't have a develop environment of macOS, I can help to check and fix updated patch on macOS.

**Comment by RobotCaleb** [comment]
Of course. I should have caught both of those, my mistake.

The first is easy
The second requires (I think, I haven't tried yet) adding a configuration option to the cmake settings to set as C++11. As the description for this project states that one of the prerequisites is a C++11 compiler, I hope this isn't a problem.

**Comment by RobotCaleb** [comment]
Further, `msgpack-c` supports including as header-only if targeting `C++11`. This would remove the dependency on linking against the `msgpack-c` library.

I won't include that with this change, however. That's up to you. We don't use your build setup, so it's not relevant to us.

**Comment by RobotCaleb** [comment]
Okay, I was mistaken about needing to fix `CMakeLists.txt`. Travis is less angry now. Please take a look. :)

**Comment by m-mizutani** [comment]
That's good! Thanks a lot for your contribution.

By the way, let me consider about `C++11` option and `msgpack-c` dependency. Thanks again for the comment.

**Pull request merged**
